## 6-е домашнее задание - Библиотека numpy

<b>Царитова Нина</b>

Группа: НПМбд-02-19  

Перед выполнением этого домашнего задания полезно прочитать про возможности и основные методы библиотеки numpy:  
http://acm.mipt.ru/twiki/bin/view/Cintro/PythonNumpy  


In [3]:
import numpy as np

1.	Создайте равномерное разбиение интервала от -1.3 до 2.5 на 64 отрезка.

In [2]:
np.linspace(-1.3,2.5,64)

array([-1.3       , -1.23968254, -1.17936508, -1.11904762, -1.05873016,
       -0.9984127 , -0.93809524, -0.87777778, -0.81746032, -0.75714286,
       -0.6968254 , -0.63650794, -0.57619048, -0.51587302, -0.45555556,
       -0.3952381 , -0.33492063, -0.27460317, -0.21428571, -0.15396825,
       -0.09365079, -0.03333333,  0.02698413,  0.08730159,  0.14761905,
        0.20793651,  0.26825397,  0.32857143,  0.38888889,  0.44920635,
        0.50952381,  0.56984127,  0.63015873,  0.69047619,  0.75079365,
        0.81111111,  0.87142857,  0.93174603,  0.99206349,  1.05238095,
        1.11269841,  1.17301587,  1.23333333,  1.29365079,  1.35396825,
        1.41428571,  1.47460317,  1.53492063,  1.5952381 ,  1.65555556,
        1.71587302,  1.77619048,  1.83650794,  1.8968254 ,  1.95714286,
        2.01746032,  2.07777778,  2.13809524,  2.1984127 ,  2.25873016,
        2.31904762,  2.37936508,  2.43968254,  2.5       ])

2.	Сгенерируйте numpy массив длины $3n$, заполненный циклически числами 1, 2, 3, 1, 2, 3, 1....

In [ ]:
n = 2
a = np.array()
for i in range(3n):
    a[i] = 1

3.	Создайте массив первых 10 нечетных целых чисел.

In [ ]:
n = 10
a = np.arange(1,n*2,2)
print(a)

4.  Создайте массив нулей размера 10 x 10, а затем создайте в нём "рамку" из единиц по краям.

In [ ]:
a = np.ones((10,10))
a[1:-1,1:-1] = 0
print(a)

5.  Создайте массив 8 x 8 с шахматной доской из нулей и единиц.

In [ ]:
a = np.zeros((8,8), dtype=int)
a[1::2,::2] = 1
a[::2,1::2] = 1
print(a)

6.  Создайте функцию, которая создает $n×n$ матрицу с $(i,j)$-элементом, равным $i+j$.

In [93]:
n = 20
m = np.arange(n**2)
print((m // n + m % n).reshape(n, n))

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
 [ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21]
 [ 3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22]
 [ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
 [ 5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
 [ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]
 [ 7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26]
 [ 8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27]
 [ 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28]
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
 [11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30]
 [12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31]
 [13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32]
 [14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32

7. Примените функцию dot для перемножения вектор на вектор, матрицу на вектор и матрицу на матрицу.

In [ ]:
a = np.arange(1, 10).reshape(3, 3)
b = np.arange(11, 20).reshape(3, 3)
c = np.array([1, 2, 3])

print('Вектор на вектор:', np.dot(c, c))
print('Матрица на вектор:',np.dot(a, c))
print('Матрица на матрицу:',np.dot(a, b))

8. Вычислите cos(x) и sin(x) на интервале [0,1] с шагом $0.05$, а затем объедините оба массива чисел как строки в один массив.

In [ ]:
m = np.arange(0, 1, 0.05)
s = np.sin(m)
c = np.cos(m)
a = np.vstack((s, c))
print(a)

9. Создайте матрицу $A$ размера $3×5$ из случайных чисел с равномерным распределением на отрезке $[-1,3]$ (используйте np.random.rand)

In [95]:
a = np.random.uniform(-1,3,15).reshape(3,5)
print(a)

[[ 0.68890702  2.33858464  0.43662611  0.5141435   2.01334136]
 [ 0.83502465  0.54657366 -0.7169442   2.0491111   2.36249855]
 [-0.79773671  0.40855886  0.01363712 -0.47614863  2.64846683]]


10. Найдите сумму всех элементов, сумму внутри строк, сумму внутри столбцов, а также среднее значение, дисперсию и стандартное отклонение чисел для каждой строки матрицы $A$. (Подобно тому, как sorted имеет необязательный аргумент key=, многие функции Numpy имеют необязательный аргумент axis=)


In [74]:
print('Сумма всех элементов = ',np.sum(a))
print('Сумма элементов в столбцах = ',np.sum(a, axis = 0)) 
print('Сумма элементов в строках = ',np.sum(a, axis = 1)) 
print('Среднее значение для каждой строки = ',np.mean(a, axis=1)) 
print('Дисперсия для каждой строки = ',np.var(a, axis=1)) 
print('Стандартное отклонение для каждой строки = ',np.std(a, axis=1)) 

Сумма всех элементов =  10.430987066527772
Сумма элементов в столбцах =  [6.44079494 0.63582478 3.35436735]
Сумма элементов в строках =  [4.30437071 2.62806045 0.24843923 1.572318   1.67779868]
Среднее значение для каждой строки =  [1.43479024 0.87602015 0.08281308 0.524106   0.55926623]
Дисперсия для каждой строки =  [0.08885439 1.12736369 0.06203678 0.7273528  2.14636141]
Стандартное отклонение для каждой строки =  [0.29808454 1.06177384 0.24907184 0.85284981 1.46504656]


11.  Отнимите от каждого элемента матрицы $A$ среднее по строке и поделите на стандартное отклонение строки.

In [99]:
a = np.random.uniform(-1,3,15).reshape(3,5)
x = np.average(a, axis=-1)
y = np.sqrt(np.var(a, axis=-1, dtype=float))
print((a - x.reshape(len(x), 1)) / y.reshape(len(y), 1))

[[ 0.95521885  0.37438166  0.24412431  0.36411408 -1.9378389 ]
 [ 1.30069843 -1.20196275 -0.34305335 -0.80410731  1.04842499]
 [-1.04531937  1.38068302 -1.08541422  0.89541449 -0.14536393]]


12. Отсортируйте матрицу $A$ по 3-ому столбцу, т.е. поменяйте местами строки матрицы так, чтобы 3-й столбец оказался отсортированным. Используйте для этого slicing + argsort + indexing.

In [97]:
a = np.random.uniform(-1,3,15).reshape(3,5).transpose()
a[a[:, 2].argsort()]

array([[ 2.45511394, -0.94911809, -0.41232801],
       [ 1.76758506,  1.38473805, -0.27730746],
       [-0.19373715, -0.54642736,  0.18578432],
       [ 2.59593738, -0.10254399,  0.3610801 ],
       [ 2.1879247 , -0.83163133,  2.88972721]])

13. Посчитайте две матрицы: $B = A^TA$ и $C = AA^T$. Что вы можете о них сказать? Какого они размера? В чём их сходство и отличие?

In [76]:
a = np.random.uniform(-1,3,15).reshape(3,5)
b = a.dot(a.T)
c = a.T.dot(a)
print('В =',b)
print('C =',c)
# обе матрицы квадратные, но разных размеров: матрица В - 5х5, матрица С - 3х3

В = [[10.90666773  5.6379743   6.05300744]
 [ 5.6379743   6.84961772  5.9737689 ]
 [ 6.05300744  5.9737689  10.11601944]]
C = [[ 1.11674887 -2.0409235  -2.38277111  0.54329014 -2.26347935]
 [-2.0409235   4.91779373  2.6314986  -0.1672846   4.46196892]
 [-2.38277111  2.6314986  11.42760735 -1.23114532  8.5468324 ]
 [ 0.54329014 -0.1672846  -1.23114532  1.16777888  0.3517507 ]
 [-2.26347935  4.46196892  8.5468324   0.3517507   9.24237607]]


14. Найдите сумму диагональных элементов матриц $B$ и $C$.

In [77]:
print('Сумма диагональных элементов матрицы В = ',np.trace(b))
print('Сумма диагональных элементов матрицы C = ',np.trace(c))

Сумма диагональных элементов матрицы В =  27.872304891351035
Сумма диагональных элементов матрицы C =  27.872304891351035


15.	Посчитайте детерминант и ранг матриц $A$, $B$ и $C$, посмотрите на спектр (набор собственных значений) матриц $B$ и $C$, какие выводы вы можете сделать?  
(подсказка: используйте готовые функции из библиотеки np.linalg). 


In [78]:
print('Ранг матрицы А = ',np.linalg.matrix_rank(a),'\nДетерминант и спектр матрицы A посчитать нельзя,т.к. матрица не квадратная ')
print('Ранг матрицы В = ',np.linalg.matrix_rank(b),'\nДетерминант матрицы В = ',np.linalg.det(b))
w, v = np.linalg.eig(b)
print ("Собственные числа матрицы В = :\n", w)
print ("Собственные векторы матрицы В = :\n", v)
print('Ранг матрицы C = ',np.linalg.matrix_rank(c),'\nДетерминант матрицы C = ',np.linalg.det(c))
w, v = np.linalg.eig(c)
print ("Собственные числа матрицы C = :", w)
print ("Собственные векторы матрицы C = :\n", v)
#Ранги всех матриц одинаковые, спектр матрицы В что-то непонятное и большезначное

Ранг матрицы А =  3 
Детерминант и спектр матрицы A посчитать нельзя,т.к. матрица не квадратная 
Ранг матрицы В =  3 
Детерминант матрицы В =  201.73020341884688
Собственные числа матрицы В = :
 [21.24995355  4.52389062  2.09846073]
Собственные векторы матрицы В = :
 [[ 0.6237949   0.74770749  0.22762564]
 [ 0.49510699 -0.15267206 -0.85531299]
 [ 0.60477185 -0.64623893  0.46543126]]
Ранг матрицы C =  3 
Детерминант матрицы C =  -6.722665460212501e-30
Собственные числа матрицы C = : [ 2.12499535e+01  4.52389062e+00  2.09846073e+00  4.32097614e-16
 -2.87133456e-16]
Собственные векторы матрицы C = :
 [[ 0.18442464 -0.17161483 -0.35250204  0.00439555  0.7378613 ]
 [-0.30697409  0.7721744   0.32228355 -0.30301767  0.10005656]
 [-0.68388706 -0.55964416  0.18533775 -0.41605882 -0.15253906]
 [ 0.03835885  0.15887346 -0.69798181 -0.6518396  -0.57876535]
 [-0.63449314  0.18934808 -0.50034682  0.55692115  0.29548586]]


16. Численно посчитать определённый интеграл  3-мя методами:  
a)	Прямоугольников $\int\limits_a^b {f(x)dx \approx \Delta x\sum\limits_{k = 0}^N {f({x_k})} }$  
b)	Трапеций $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{2}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N - 1} {f({x_k})}  + f({x_N})} \right)}$  
c)	По правилу Симпсона  $\int\limits_a^b {f(x)dx \approx \frac{{\Delta x}}{3}\left( {f({x_0}) + 2\sum\limits_{k = 1}^{N/2 - 1} {f({x_{2k}})}  + 4\sum\limits_{k = 1}^{N/2} {f({x_{2k - 1}})}  + f({x_N})} \right)}$  


В реализации этих методов цикл for для суммирования использовать нельзя.  
Нужно посчитать значение интеграла с некоторым шагом интегрирования (например начать с 0.1), потом уменьшить его в десять раз и ещё раз посчитать и так до тех пор пока отличие в ответах будет в 5-м знаке после запятой, т.е. чтобы ошибка была меньше 1e-5. Получить ответы для 3-х разных методов и сделать соответствующие выводы.  

Далее необходимо сравнить полученные оценки с аналитическим решением (т.е. формульным, которое вы должны сами посчитать на листочке и вбить формулу-ответ).   

В качестве интеграла взять один из следующих с номером, сгенерированным случайным образом с помощью функции np.random.randint(10), в качестве seed для генератора случайных чисел взять номер своего студенческого билета.

<table width="80%"
       align="center">
    <tr>
        <td> 0) $\int\limits_3^4 {\frac{{{x^2} + 3}}{{x - 2}}dx}$ </td>
        <td> 1) $\int\limits_{ - 2}^{ - 1} {\frac{{x + 1}}{{{x^3} - {x^2}}}dx}$ </td>
        <td> 2) $\int\limits_1^2 {\frac{{{e^{1/{x^2}}}}}{{{x^3}}}dx}$ </td>
        <td> 3) $\int\limits_1^e {\frac{{\cos (\ln x)}}{x}dx}$ </td>
        <td> 4) $\int\limits_1^e {\frac{{dx}}{{x(1 + {{\ln }^2}x)}}}$ </td>
    </tr>                
    <tr>
        <td> 5) $\int\limits_0^{\pi /2} {{{\cos }^3}\alpha \;d\alpha }$ </td>
        <td> 6) $\int\limits_0^{1/3} {c{h^2}3x\;dx}$ </td>
        <td> 7) $\int\limits_2^3 {\frac{{dy}}{{{y^2} - 2y - 8}}dy}$ </td>
        <td> 8) $\int\limits_{3/4}^2 {\frac{{dx}}{{\sqrt {2 + 3x - 2{x^2}} }}}$ </td>
        <td> 9) $\int\limits_0^2 {\frac{{2x - 1}}{{2x + 1}}dx}$ </td>
        </tr>
</table>

In [31]:
np.random.randint(10)

0

In [32]:
def f(x):
    return (x + 1) / (x - 2)

def p(f, a, b, sh):
    x = np.linspace(a, b - sh, int((b - a) / sh))
    y = sh * f(x) 
    return np.sum(y)

def t(f, a, b, sh):
    x = np.linspace(a, b, int((b - a) / sh) + 1)
    y = f(x[0]) + 2 * np.sum(f(x[1:-1])) + f(x[-1])
    return y * sh / 2

def s(f, a, b, sh):
    x = np.linspace(a, b, int((b - a) / sh) + 1)
    y = f(x[0]) + 4 * np.sum(f(x[1:-1:2])) + 2 * np.sum(f(x[2:-1:2])) + f(x[-1])
    return y * sh / 3

In [35]:
print('Метод прямоугольников:', p(f, 3, 4, 0.01))
print('Метод трапеций:', t(f, 3, 4, 0.001))
print('Метод Симпсона:', s(f, 3, 4, 0.0001))

Метод прямоугольников: 3.086960291445473
Метод трапеций: 3.0794417291798126
Метод Симпсона: 3.079441541679836
